services:
  postgres:
    image: postgres:16-alpine
    container_name: signalstack-db
    restart: always
    environment:
      POSTGRES_DB: signalstack
      POSTGRES_USER: signal
      POSTGRES_PASSWORD: signal
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U signal -d signalstack"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: signalstack-redis
    restart: always

  # --- The API Tier (Can be scaled to multiple replicas) ---
  api:
    build: ./backend
    container_name: signalstack-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://signal:signal@postgres:5432/signalstack"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      FRONTEND_URL: "https://signal.fazleyrabbi.xyz"
      NODE_ENV: "production"
      DISABLE_SCHEDULER: "true" # !! Important: This instance handles traffic only !!
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  # --- The Background Tier (Always only 1 instance) ---
  scheduler:
    build: ./backend
    container_name: signalstack-scheduler
    restart: always
    environment:
      DATABASE_URL: "postgresql://signal:signal@postgres:5432/signalstack"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      NODE_ENV: "production"
      DISABLE_SCHEDULER: "false" # !! This instance handles the cycle !!
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build: ./frontend
    container_name: signalstack-frontend
    restart: always
    ports:
      - "3001:3001"
    environment:
      API_BACKEND_URL: http://api:3000
      NODE_ENV: "production"
    depends_on:
      - api

volumes:
  pgdata:
