name: Deploy to VPS

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name: Deploy
        run: |
          cd ${{ secrets.VPS_PROJECT_PATH }}
          ./scripts/deploy.sh
